[network]
name = "devnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 100_000_000_000_000
# Secret key: 753b7cc01a1a2e86221266a154af739463fce51219d97e4f856cd7200c3bd2a601
# Public key: 0390a5cac7c33fda49f70bc1b0866fa0ba7a9440d9de647fecb8132ceb76a94ddd
# Address: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild"
balance = 100_000_000_000_000
# Secret key: 7287ba251d44a4d3fd9276c88ce34c5c52a038955511cccaf77e61068649c17801
# Public key: 0350c9b3c8e8b3c7b3c8e8b3c7b3c8e8b3c7b3c8e8b3c7b3c8e8b3c7b3c8e8b3c7
# Address: ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5

[accounts.wallet_2]
mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital"
balance = 100_000_000_000_000
# Secret key: 530d9f61984c888536871c6573073bdfc0058896dc1adfe9a6a10dfb9c9f6a1901
# Public key: 0340c9b3c8e8b3c7b3c8e8b3c7b3c8e8b3c7b3c8e8b3c7b3c8e8b3c7b3c8e8b3c7
# Address: ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG

[accounts.wallet_3]
mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom scorpion tower claim oppose clever elephant dinosaur eight problem before frozen dune wagon high"
balance = 100_000_000_000_000
# Secret key: d655b2523bcd65e34889725c73064feb17ceb796831c0e111ba1a552b0f31b3901
# Public key: 0330c9b3c8e8b3c7b3c8e8b3c7b3c8e8b3c7b3c8e8b3c7b3c8e8b3c7b3c8e8b3c7
# Address: ST2JHG361ZXG51QTQAVC8QJQXZQHQHQHQHQHQHQHQ

[devnet]
disable_stacks_explorer = false
disable_stacks_api = false
# Use a custom working directory for the devnet
# working_dir = "tmp/devnet"

# Set the epoch 2.0 transition height to 102
epoch_2_0 = 102
# Set the epoch 2.05 transition height to 103  
epoch_2_05 = 103
# Set the epoch 2.1 transition height to 104
epoch_2_1 = 104
# Set the epoch 2.2 transition height to 105
epoch_2_2 = 105
# Set the epoch 2.3 transition height to 106
epoch_2_3 = 106
# Set the epoch 2.4 transition height to 107
epoch_2_4 = 107

[devnet.orchestrator]
# Specify a custom docker image to use for the orchestrator
# docker_image = "hirosystems/stacks-blockchain:latest"

[devnet.bitcoin_node]
# Specify a custom docker image to use for the bitcoin node
# docker_image = "bitcoind:latest"
